version: '3.7'

services:
  mlflow:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:password@postgres/mlflow
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - C:\Dev-IA\DetectionPannes\docker\mlflow\mlflow_data:/mlflow/artifacts  # Sauvegarde des artefacts MLflow
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - C:\Dev-IA\DetectionPannes\docker\mlflow\pg_data:/var/lib/postgresql/data  # Sauvegarde de la base PostgreSQL
